/**
 * Fretboard action types
 * @type {string}
 */
export const FRETBOARD_CHANGE_TUNING = "FRETBOARD_CHANGE_TUNING";
export const FRETBOARD_CALCULATE_NOTES = "FRETBOARD_CALCULATE_NOTES";
export const FRETBOARD_TOGGLE_AUDIO = "FRETBOARD_TOGGLE_AUDIO";
export const FRETBOARD_ADD_SELECTED = "FRETBOARD_ADD_SELECTED";
export const FRETBOARD_DELETE_SELECTED = "FRETBOARD_DELETE_SELECTED";
export const FRETBOARD_DELETE_ALL_SELECTED = "FRETBOARD_DELETE_ALL_SELECTED";


/**
 * Keyboard action types
 * @type {string}
 */
export const KEYBOARD_HIGHLIGHT_SELECTION = "KEYBOARD_HIGHLIGHT_SELECTION";
export const KEYBOARD_CLEAR_SELECTION = "KEYBOARD_CLEAR_SELECTION";
export const KEYBOARD_TOGGLE_LAPTOP_KEYBOARD = "KEYBOARD_TOGGLE_LAPTOP_KEYBOARD";


/**
 * Chordbank action types
 * @type {string}
 */
export const CHORDBANK_ADD_NOTE = "CHORDBANK_ADD_NOTE";
export const CHORDBANK_DELETE_NOTE = "CHORDBANK_DELETE_NOTE";
export const CHORDBANK_POPULATE_POSSIBLE_CHORDS = "CHORDBANK_POPULATE_POSSIBLE_CHORDS";
export const CHORDBANK_TOGGLE_EXACT_MATCHING = "CHORDBANK_TOGGLE_EXACT_MATCHING";
export const CHORDBANK_CLEAR_ALL_NOTES = "CHORDBANK_CLEAR_ALL_NOTES";
export const CHORDBANK_SELECTED_CHORD_NAME = "CHORDBANK_SELECTED_CHORD_NAME";